### ISSUE TITLE
Unify Coin3D & FreeCAD pivy repos

### ISSUE THREAD

**Issue by kkremitzki** [coin3d/pivy#60]
The Coin3D organization's migration to GitHub is now basically complete, and pivy is now maintained with git: https://github.com/coin3d/pivy

Therefore we should aim to upstream changes in FreeCAD's pivy repo and move maintenance from this fork to there.

I've already upstreamed the patches used in the Debian package and made a 0.6.5 release. I'm working on getting CI fixed as well.

**Comment by looooo** [comment]
What should I say? Making a 0.6.5 release without all the changes from this repo is messing up the release history! I tried to integrate the Debian-patches to this repo as well. I guess now we have two divorced tips and extra work is necessary to get them aligned again. I am willing to bring the changes back to the main repo, but not if things are done in such an ignorant way. So please remove the 0.6.5 release until the changes of this repo are applied correctly.

**Comment by kkremitzki** [comment]
Sorry, I'm just getting ahead of myself. I can do the integration of the changes here into the main repo, also--I mainly wanted to let you know that things are ready to begin now that the migration has happened. I've deleted the tag and reverted the commit moving the tip to 0.6.6a0.

**Comment by looooo** [comment]
@kkremitzki Is there any reason why not using this repo as the default? Maybe also @VolkerEnderlein can join this discussion.

I am willing to transfer the work done in this repo. But I don't like the way it is done currently. A lot of PR's from this repo were backported to bitbucket and now have different hashes (and some also have a  different author, although this is not a big point for me) due to transferring to github again, which in turn will result in merge conflicts (If we try to apply the 30 currently missing commits). I don't see any reason why we should not use this repo as the default and add missing PR's on top of it (there are not a lot of them). So I suggest the following:
Delete the current coin3d/pivy repo and someone from the freecad-admins will transfer this repo to the coin3d organization (I can't do that as I don't have admin rights for this repo). Then apply the missing commits (or redo them, it's not a lot of diff).

**Comment by kkremitzki** [comment]
That seems reasonable enough. I'll note that I have the necessary permissions to move this repo and will just wait for Volker to chime in.

**Comment by VolkerEnderlein** [comment]
@looooo, @kkremitzki Yes, I fully agree. We should use the FreeCAD repo instead of the 'ported' pivy repo from Coin3D. I will delete the pivy repo and happily accept the transfer. Kurt, can you give me a go?  Cheers

**Comment by kkremitzki** [comment]
Sure, go for it.

**Comment by VolkerEnderlein** [comment]
Done!

**Comment by kkremitzki** [comment]
Alright, it's moved. There are 3 open issues on Bitbucket which are no longer present here. Should we just copy & paste their contents or would it be easy to adapt your script to re-add them?

**Comment by kkremitzki** [comment]
Also, @looooo should probably be added to the Coin3d organization right?

**Comment by VolkerEnderlein** [comment]
I think the 3 open issues should be transferred manually. Adding @looooo to the Coin3d team can be done by @WizzerWorks or @veelo.

**Comment by kkremitzki** [comment]
OK, I'll add them.

**Comment by looooo** [comment]
Thanks @kkremitzki and @VolkerEnderlein . For the 0.6.5 release,  we should reconfigure travis, add some missing commits from the bitbucket repo: https://github.com/coin3d/pivy/pull/65 and test if everything works for the target platforms (debian, conda, maybe others). Do you have any other TODO's?

For the next release 0.6.6 we might try to use cmake as configuration tool to make the library more consistent with the other coin-related libraries: https://github.com/coin3d/pivy/issues/59

**Comment by veelo** [comment]
> Adding @looooo to the Coin3d team can be done by @WizzerWorks or @veelo.

I have sent an invite.

**Comment by looooo** [comment]
@VolkerEnderlein @kkremitzki thanks for transferring the FreeCAD/pivy repo to coin3d. From my side, everything is ready for a 0.6.5 release.

**Comment by kkremitzki** [comment]
+1 from me as well. I'll go ahead and create a tag.
